# Generated by Django 5.2.6 on 2025-09-20 02:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradingResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_score", models.IntegerField()),
                ("max_score", models.IntegerField()),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("correctness_score", models.IntegerField()),
                ("correctness_max", models.IntegerField(default=40)),
                ("correctness_feedback", models.TextField()),
                ("code_style_score", models.IntegerField()),
                ("code_style_max", models.IntegerField(default=25)),
                ("code_style_feedback", models.TextField()),
                ("efficiency_score", models.IntegerField()),
                ("efficiency_max", models.IntegerField(default=20)),
                ("efficiency_feedback", models.TextField()),
                ("documentation_score", models.IntegerField()),
                ("documentation_max", models.IntegerField(default=15)),
                ("documentation_feedback", models.TextField()),
                ("overall_feedback", models.TextField()),
                ("suggestions", models.TextField(blank=True)),
                (
                    "ai_model_used",
                    models.CharField(default="claude-3-sonnet", max_length=50),
                ),
                ("processing_time", models.FloatField()),
                ("graded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_result",
                        to="submissions.studentsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["-graded_at"],
            },
        ),
    ]
