# Generated by Django 5.2.6 on 2025-09-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0002_gradingresult_compilation_result_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradingresult",
            name="custom_rubric",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
