# Generated by Django 5.2.6 on 2025-09-29 02:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0003_gradingresult_custom_rubric"),
        ("submissions", "0003_remove_student_student_id_alter_student_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchGradingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_files", models.IntegerField(default=0)),
                ("processed_files", models.IntegerField(default=0)),
                ("successful_grades", models.IntegerField(default=0)),
                ("failed_grades", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("average_score", models.FloatField(blank=True, null=True)),
                ("highest_score", models.FloatField(blank=True, null=True)),
                ("lowest_score", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submissions.assignment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
