# Generated by Django 5.2.6 on 2025-09-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0004_batchgradingjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchgradingjob",
            name="assignment_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
