# Generated by Django 5.2.6 on 2025-09-20 02:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "reference_file",
                    models.FileField(
                        upload_to="reference_answers/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["cpp", "cc", "cxx"]
                            )
                        ],
                    ),
                ),
                ("max_score", models.IntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("student_id", models.CharField(max_length=50)),
                (
                    "code_file",
                    models.FileField(
                        upload_to="submissions/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["cpp", "cc", "cxx"]
                            )
                        ],
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("grading", "Grading"),
                            ("graded", "Graded"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("total_score", models.IntegerField(blank=True, null=True)),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="submissions.assignment",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
