# Generated by Django 5.2.6 on 2025-09-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_remove_studentsubmission_student_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="student_id",
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
