# Generated by Django 5.2.6 on 2025-09-29 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0004_batchgradingjob"),
        ("submissions", "0003_remove_student_student_id_alter_student_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubmission",
            name="batch_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="grading.batchgradingjob",
            ),
        ),
    ]
